feat: 공고 상세 및 업로드 관련 2차 MVP 기능 구현
DDD-Community/DDD-11-Dissonance-iOS pull request #43
Opened 2024-11-18 08:22 UTC by Hansangjin98

### 📌 관련 이슈 번호
 - #40 

<br>

# 📘 작업 유형
 - [x] 신규 기능 추가

<br>

# 📙 작업 내역 (구현 내용 및 작업 내역을 기재합니다.)
 - 공고 업로드 화면 UI 변경사항 반영
 - 공고 수정 기능 구현
 - 공고 삭제 기능 구현

<br>

### 📋 체크리스트 (PR을 올리기 전에 스스로 확인해봐요!)
 - PR 제목에 작업 내용을 요약하여 기재했는가?
 - 코딩컨벤션을 준수하는가?
 - 내 코드에 대해 스스로 검토를 했는가?

2024-11-19 10:49 UTC, wongbingg requested changes
상진님 몇가지 코멘트 남겨두었습니다~! 고생하셨습니다!

2024-11-19 10:49 UTC, wongbingg commented on Targets/DomainLayer/Sources/UseCases/PostDetailUseCase.swift
> +  }
네트워크 요청 플로우가 아래 분기가 맞을까요?
1.  statusCode 범위가 200..<300     => .success
2. statusCode 범위가 300...              => .error(message)
3. 서버통신 에러로 provider.rx.request 에서 fail 시   => .catchAndReturnNetworkError()

2024-11-22 08:13 UTC, Hansangjin98 commented on Targets/PresentationLayer/Sources/PostDetail/View/PostDetailViewController.swift
> +      .disposed(by: disposeBag)
true가 한 번이라도 방출되면 화면이 나가지고 VC가 deinit 되기 때문에 문제가 되진 않을 거라 판단했습니다!

2024-11-22 08:17 UTC, Hansangjin98 commented on Targets/DesignSystem/Sources/Component/Common/MozipTextField.swift
> +
헉 그렇네요 확인 감사합니다!!

2024-11-22 08:19 UTC, Hansangjin98 commented on Targets/DomainLayer/Sources/UseCases/PostDetailUseCase.swift
> +  }
네 일단 그렇게 생각하고 작성했는데 중복 코드가 자꾸 생기는 느낌이라.. 효율적으로 처리할 방법을 좀 더 고민해봐야겠다는 생각이 드네요!

2024-11-23 01:11 UTC, wongbingg commented on Targets/DomainLayer/Sources/UseCases/PostDetailUseCase.swift
> +  }
error 타입 변환 과정을 network 레이어에 맡기고 Usecase 단에서는 Observable<Entity> 타입으로 반환하는 것이 더 좋겠다는 생각이 드네요! 추후 회의에서 같이 고민해보면 좋겠네요

2024-11-23 08:24 UTC, merged